### ISSUE TITLE
Can't access myo64.dll

### ISSUE THREAD

**Issue by R-i-k** [NicholasAStuart/myo-java#18]
Hi Nicholas,

I want to check if MyoConnect is up and running before I use it in my program.
To do that, I catch RuntimeException in initialization the new Hub() and tell user to turn on MyoConnect. 
The error occurs when I initiate new Hub() again. 
It cannot access myo64.dll, because it is still being used from the first, not complete, initialization. Whether is MyoConnect on or off.

Could you tell me the right way how to achieve my plan? Or can it be corrected somehow? 

Thank you for your response :) 
Richard

**Comment by NicholasAStuart** [comment]
I haven't been active in the development of this library for a while due to Thalmics lack of updates to their API's. I don't see anything in the [API](https://developer.thalmic.com/docs/api_reference/platform/release-notes.html) about exceptions, but can try to dig into the code. 

I recreated the exception:
```
Error: 
java.lang.RuntimeException: Unable to connect to Myo Connect. Is Myo Connect running?
	at com.thalmic.myo.Hub.initialize(Native Method)
	at com.thalmic.myo.Hub.<init>(Hub.java:28)
	at com.thalmic.myo.example.HelloMyo.main(HelloMyo.java:16)
```

Looking at the [JNI code](https://github.com/NicholasAStuart/myo-java-JNI-Library/blob/master/com_thalmic_myo_Hub.cpp) that is throwing the RuntimeException, it looks like it is catching _an_ exception, and displaying the message. You could file an Issue or PR over on the [myo-java-JNI-Library](https://github.com/NicholasAStuart/myo-java-JNI-Library/) to enhance the exception thrown here to be more specific than a RuntimeException.

I'm not sure why calling `myo::Hub` would throw an exception, as trying to look down the rabbit hole resolves to the hub initiation in `libmyo.h` returning a status object, not throwing an exception.

**Comment by R-i-k** [comment]
I solved my problem with reading the result of  `tasklist /fi "imagename eq Myo Connect.exe"` from batch file. I think this is a reliable solution and I don't need to catch any exception.

Anyway, thank you for your answer :) 
Have a nice day.
